apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: ns-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: nums
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: root
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: ns-19
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: ns-19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: iliyahse/miemhomeworkrestachivment2:1.4
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: postgresql-service
        - name: POSTGRES_DB
          value: nums
        - name: POSTGRES_USER
          value: user
        - name: POSTGRES_PASSWORD
          value: root
        - name: DB_PORT
          value: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: ns-07
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort
